<?php 

    $name =   explode(' ',$block->getCustomerName()); 
    $firstname = $name[0];
    $lastname = $name[1];
    $email =   $block->getCustomerEmail(); 
?>
<form class="form customform"
      action="<?php echo $block->getBaseUrl().'customform/index/save'; ?>"
      id="magelearn-customform-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      enctype="multipart/form-data"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
    	<!--<legend class="legend"><span><?= $block->escapeHtml(__('Customer Feedback Form ')) ?><a href="<?php echo $block->getBaseUrl().'customform/index/list'; ?>">(Visit List Page)</a></span></legend><br>-->
        <div class="field note no-label"><?= $block->escapeHtml(__('Fillup your Feedback form.')) ?></div>
        <div class="field first_name required">
            <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First name:')) ?></span></label>
            <div class="control">
                <input name="first_name" 
                       id="first_name" 
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" 
                       class="input-text" 
                       type="text" 
                       data-validate="{required:true}"
                       value="<?php echo $name[0];?>"/>
            </div>
        </div>
        <div class="field last_name required">
            <label class="label" for="last_name"><span><?= $block->escapeHtml(__('Last name:')) ?></span></label>
            <div class="control">
                <input name="last_name" 
                       id="last_name" 
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" 
                       class="input-text" 
                       type="text" 
                       data-validate="{required:true}"
                       value="<?php echo $name[1];?>"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" 
                       id="email" 
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text" 
                       type="email" 
                       data-validate="{required:true, 'validate-email':true}"
                       value="<?php echo $email; ?>"/>
            </div>
        </div>
        <div class="field message required">
            <label class="label" for="message"><span><?= $block->escapeHtml(__('Comment:')) ?></span></label>
            <div class="control">
                <textarea name="message" id="message" title="<?= $block->escapeHtml(__('Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

