<!DOCTYPE html>
<html>
<body>
	<?php
		/**
		 * @var \Magelearn\Customform\Block\Cms\Index $block
		 */
		$feedbackcollection = $block->getFeedbackCollections();
		if(sizeof($feedbackcollection)>0)
		{
			$div = '';
			$div.='<section class="homepage slider">';
			
				foreach ($feedbackcollection as $feedback) 
				{
					$dataarr = $feedback->getData();
					$div.='<div>';
					$div.='<center><h2>'.$dataarr['message'] .'</h2></center>';
					$div.='</div>';			
				}				
			$div.='</section>';
			echo $div;
		}
	?>
	
</body>
</html>